spring:
  application:
    name: Helio
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=helio;encrypt=false
    username: sa
    password: Sql@1234567
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sudhakarofficial2004@gmail.com
    password: "wswi dxti sqdz hpdx"
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

twilio:
  accountSid: AC59721155187b75e480907b7e33e3e0d5
  authToken: 22e5b68f0bdb84936598e955d8a52efd
  sender-mobile-number: +19203102629

rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHSncmZwvKqhaI5xlu1vZadzHMDzQGbHQyEx+nX3go1tcLRoS6JiIYb+rf/zpvEnHVInCF9dktbSY17Dgst5YgrGEvNliWs0xqbQ/EJ3C7CWWXMFTbu/NVoORF2wVH0pVndWWnH3qMMHKkIfUSgNSBnEfJ8H9sDZzSJoR7gKWUXeEtW1K9AkSL/gzhkioTG9Y2JadU2KO2N9IJ3vq5nldJCcWU9QAEQnRWUcTdvzGAzP3WXDOUrH0mTbXXEc99Vx2uywk55X+biUzNhnMBR/rgzNoJ2ZIjW3kZd3MRC5izRtVnomPoLuCft7pMUgNoNfvikMq97ini6A6zbK7uGyywIDAQAB
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCcdKdyZnC8qqFojnGW7W9lp3McwPNAZsdDITH6dfeCjW1wtGhLomIhhv6t//Om8ScdUicIX12S1tJjXsOCy3liCsYS82WJazTGptD8QncLsJZZcwVNu781Wg5EXbBUfSlWd1ZacfeowwcqQh9RKA1IGcR8nwf2wNnNImhHuApZRd4S1bUr0CRIv+DOGSKhMb1jYlp1TYo7Y30gne+rmeV0kJxZT1AARCdFZRxN2/MYDM/dZcM5SsfSZNtdcRz31XHa7LCTnlf5uJTM2GcwFH+uDM2gnZkiNbeRl3cxELmLNG1WeiY+gu4J+3ukxSA2g1++KQyr3uKeLoDrNsru4bLLAgMBAAECggEAEOc3ihAQQQnsS1gMZKJ9ZQ2szZ/5B+2yvIlzFVy2Y3f1KXaMSBOgp3+mt1TOVax7LdtI1Uo8WVd1PoAn/lMOZ63DTZvXTfvzpTyzmnVx2CT5cWuQWKAendx/axp2KQKmuy1EepwShjyf4wxmxsVdffsus8oYuauHPHbprknvcEqFX4ya8dW9b4Z3FsWRxtpReSrO0xxUSdcq6eXlx51renLcFATPB/P4/8PQRnY+jo1OHtOGeETMaTRvQY4x+52W5P4qi/yKwf+vQtNiN6xalnPU1LS/QJOh7wK0/7FIXpGOfB2qEbgpoFhKdmQVFtx4i+KXNrvkqnWwlTilkCw3cQKBgQDHtDRCck2D2HKC7+1eW0FxIWrZuBT7LtfPErLrStpsXc1ku2yvoAWzmGz+JFyL+JY/VIvvEgnQc7/FQw/PT73Py3oWin0tu6s2xVfrc8TD86oueQzIrEJk/TCloXL/hdCId1xUuwaQIfc3peaQdUg1TSgQj+Trlicb3cwLNQ+KuwKBgQDIj2fHteyWz8r3nHPOF56uzOcbShPmjr5hBbxQz3xGPaK/nt2UuXCVWJa2jFQR0i9581wx/BMBh4Gee4OT1299qq4BBPyMcIuvirSZol4BXu627O++EFt38P27XXVEKLeJxWwpNpxMPnfA8WG3go2anpdVnnCvhVTbTXn6blqfMQKBgFo5bzbp/11m5+2CSoLLxdg/2c99nHUTZ8sVTqKBUgeNpaMyDluWd5z5a5yyfuF6MR9xqjsbsjVsZiLQNo9aHo6IBqOyc/W6iRMYu60Tw70oFCYk6IKtWN3ZiiX6uEL7iQhurNdXHBL4VYHdwTpY0oPKVSSObkWFtCuh3HLfySLLAoGBAI/52q+UmvYcz4D30G6HqEOmFtYRVL3zhRnTaz+742PtRVM4MatdgEPGJ9N+Y6+zap+qI2pCokY7x8JEus08H+5fw7A5qy8KcEyhT0rnM4LaapXo+6Y+ydsNpqiFy/QVIsUFc8MWUBev1HovDk4Vq5/u74boSc7G8YbJVKKB7A5RAoGBAKQrQVvm5UIVXYXKeT8FNbxgNNRC0slB0RvXU6r6bWip3qcDJ/zftQRsXF0kPTmlJkVqlWwDgkHTF0L+mFSUnB6g88aM3hW6mz5mqCMbjasHZVk3cIKYvk3hgRr8aJ4XqtCN5DyerhKYxnIoKo7cFV3TKhhcgmbfAyFvB7yOQBMO

application-id: f1246c09-02c3-43db-ad31-52ff1676b2e0
