spring:
  application:
    name: Helio
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=helio;encrypt=false
    username: sa
    password: Sql@1234567
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sudhakarofficial2004@gmail.com
    password: "wswi dxti sqdz hpdx"
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true


application-id: f1246c09-02c3-43db-ad31-52ff1676b2e0
